/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VulcanizarePacurariRouteImport } from './routes/vulcanizare-pacurari'
import { Route as VulcanizareMobilaMiroslavaRouteImport } from './routes/vulcanizare-mobila-miroslava'
import { Route as TermeniRouteImport } from './routes/termeni'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapLocatiiDotxmlRouteImport } from './routes/sitemap-locatii[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const VulcanizarePacurariRoute = VulcanizarePacurariRouteImport.update({
  id: '/vulcanizare-pacurari',
  path: '/vulcanizare-pacurari',
  getParentRoute: () => rootRouteImport,
} as any)
const VulcanizareMobilaMiroslavaRoute =
  VulcanizareMobilaMiroslavaRouteImport.update({
    id: '/vulcanizare-mobila-miroslava',
    path: '/vulcanizare-mobila-miroslava',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermeniRoute = TermeniRouteImport.update({
  id: '/termeni',
  path: '/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapLocatiiDotxmlRoute = SitemapLocatiiDotxmlRouteImport.update({
  id: '/sitemap-locatii.xml',
  path: '/sitemap-locatii.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/gdpr': typeof GdprRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-locatii.xml': typeof SitemapLocatiiDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni': typeof TermeniRoute
  '/vulcanizare-mobila-miroslava': typeof VulcanizareMobilaMiroslavaRoute
  '/vulcanizare-pacurari': typeof VulcanizarePacurariRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/gdpr': typeof GdprRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-locatii.xml': typeof SitemapLocatiiDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni': typeof TermeniRoute
  '/vulcanizare-mobila-miroslava': typeof VulcanizareMobilaMiroslavaRoute
  '/vulcanizare-pacurari': typeof VulcanizarePacurariRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/gdpr': typeof GdprRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-locatii.xml': typeof SitemapLocatiiDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni': typeof TermeniRoute
  '/vulcanizare-mobila-miroslava': typeof VulcanizareMobilaMiroslavaRoute
  '/vulcanizare-pacurari': typeof VulcanizarePacurariRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/gdpr'
    | '/llms.txt'
    | '/rss.xml'
    | '/sitemap-index.xml'
    | '/sitemap-locatii.xml'
    | '/sitemap.xml'
    | '/termeni'
    | '/vulcanizare-mobila-miroslava'
    | '/vulcanizare-pacurari'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/gdpr'
    | '/llms.txt'
    | '/rss.xml'
    | '/sitemap-index.xml'
    | '/sitemap-locatii.xml'
    | '/sitemap.xml'
    | '/termeni'
    | '/vulcanizare-mobila-miroslava'
    | '/vulcanizare-pacurari'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/gdpr'
    | '/llms.txt'
    | '/rss.xml'
    | '/sitemap-index.xml'
    | '/sitemap-locatii.xml'
    | '/sitemap.xml'
    | '/termeni'
    | '/vulcanizare-mobila-miroslava'
    | '/vulcanizare-pacurari'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  GdprRoute: typeof GdprRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapLocatiiDotxmlRoute: typeof SitemapLocatiiDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermeniRoute: typeof TermeniRoute
  VulcanizareMobilaMiroslavaRoute: typeof VulcanizareMobilaMiroslavaRoute
  VulcanizarePacurariRoute: typeof VulcanizarePacurariRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vulcanizare-pacurari': {
      id: '/vulcanizare-pacurari'
      path: '/vulcanizare-pacurari'
      fullPath: '/vulcanizare-pacurari'
      preLoaderRoute: typeof VulcanizarePacurariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulcanizare-mobila-miroslava': {
      id: '/vulcanizare-mobila-miroslava'
      path: '/vulcanizare-mobila-miroslava'
      fullPath: '/vulcanizare-mobila-miroslava'
      preLoaderRoute: typeof VulcanizareMobilaMiroslavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni': {
      id: '/termeni'
      path: '/termeni'
      fullPath: '/termeni'
      preLoaderRoute: typeof TermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-locatii.xml': {
      id: '/sitemap-locatii.xml'
      path: '/sitemap-locatii.xml'
      fullPath: '/sitemap-locatii.xml'
      preLoaderRoute: typeof SitemapLocatiiDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  GdprRoute: GdprRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapLocatiiDotxmlRoute: SitemapLocatiiDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermeniRoute: TermeniRoute,
  VulcanizareMobilaMiroslavaRoute: VulcanizareMobilaMiroslavaRoute,
  VulcanizarePacurariRoute: VulcanizarePacurariRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
